# Generated by Django 3.0.8 on 2020-07-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200709_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_active',
            field=models.BooleanField(default=False),
        ),
    ]
